name: acarreo_app
description: Una aplicación para manejos de transporte de carga.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_modular: ^6.3.2
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^9.0.3
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
