from .ExampleService import ExampleService
from .CamionesService import CamionesService
from .MaterialesService import MaterialesService
from .ClientesService import ClientesService
from .ObrasService import ObrasService
from .TransportistasService import TransportistasService
from .ChecadoresService import ChecadoresService
from .UbicacionesService import UbicacionesService
from .TicketsService import TicketsService
from .TicketsrecepcionService import TicketsrecepcionService

from .EmpresaExplotadoraService import EmpresaexplotadoraService
from .CustomerService import CustomerService
from .TicketMaterialSupplierService import TicketmaterialsupplierService