version: "3"

services:
  acarreocorebackend:
    image: acarreocorebackend
    container_name: acarreocorebackend

    env_file: ".env"
    environment:
      PYTHONUNBUFFERED: 1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ".:/code"
